# Generated by Django 2.2.5 on 2021-05-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210512_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('Transaction_Type', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
